###### OLD MOBILE MAKEFILE #######
#  TODO: figure out solution for ios cross compilation
extend = "../../Makefile.toml"

[tasks.package-release]
private = true
dependencies = ["clean-old-artifacts", "build-release-android"]
workspace = false
run_task = { name = ["package-artifacts"] }

[tasks.package-artifacts]
private = true
workspace = false
script_runner = "@shell"
script.main = "cp ../../target/release/apk/AspenHalls.apk ../../package"

[tasks.build-release-android]
private = true
workspace = false
condition.env_set = ["BUNDLETOOL_PATH", "ANDROID_NDK_ROOT", "JAVA_HOME"]
command = "cargo"
args = [
  "apk",
  "build",
  "--release",
  "--package=aspen_halls_mobile",
  # "--features=develop",
]

[tasks.clean-old-artifacts]
private = true
workspace = false
script_runner = "@shell"
script.main = "rm -rf ../../package/AspenHalls.apk"
