###### OLD MOBILE MAKEFILE #######
#  TODO: figure out solution for ios cross compilation
extend = "../../Makefile.toml"

[tasks.package-release]
private = true
dependencies = ["clean-old-artifacts", "build-release-android"]
workspace = false
run_task = { name = ["package-artifacts"] }

[tasks.package-artifacts]
private = true
workspace = false
script_runner = "@shell"
script.main = "cp ./android-project/app/build/outputs/apk/release/app-release.apk ../../package/Aspenhalls.apk"

[tasks.build-release-android]
private = false
workspace = false
condition.env_set = ["BUNDLETOOL_PATH", "ANDROID_NDK_ROOT", "JAVA_HOME"]
script_runner = "@shell"
script.pre = "cargo ndk -t arm64-v8a -o android-project/app/src/main/jniLibs build --release"
script.main = "gradle -p android-project assembleRelease"
script.post = "cp ./android-project/app/build/outputs/apk/release/app-release.apk ../../package"


[tasks.clean-old-artifacts]
private = true
workspace = false
script_runner = "@shell"
script.main = "rm -rf ../../package/AspenHalls.apk"
