###### OLD WASM MAKEFILE #######
extend = "../../Makefile.toml"

[tasks.package-release]
private = true
workspace = false
script_runner = "@shell"
script.main = "echo 'wasm packaging disabled due too toolchain issues'"

# dependencies = ["build-release-wasm"]
# run_task = { name = ["package-wasm-artifacts"] }

[tasks.build-release-wasm]
command = "trunk"
args = ["build", "--release"]

[tasks.package-wasm-artifacts]
private = true
script_runner = "@shell"
script.main = "zip -r ../../package/aspen_wasm.zip dist/*"
